### ISSUE TITLE
UNMET PEER DEPENDENCY zone.js@0.6.26

### ISSUE THREAD

**Issue by mhabsaoui** [openminted/omtd-platform#3]
Just got this unmet dependency with angular/* : "~2.0.1"

==> just update all occurrences of "~2.0.1" to "^2.3.1" and it's ok.

info: https://github.com/angular/angular-cli/pull/4473

**Comment by mhabsaoui** [comment]
New problem when building with 'npm run build':

`node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
node_modules/rxjs/observable/dom/WebSocketSubject.d.ts(23,22): error TS2415: Class 'WebSocketSubject<T>' incorrectly extends base class 'AnonymousSubject<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<T>'.
      Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
        Types of property 'operator' are incompatible.
          Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
            Type 'R' is not assignable to type 'T'.

npm ERR! Linux 4.10.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! openminted-platform@1.0.0 build: `npm run clean && tsc`
npm ERR! Exit status 2
`

Thanks.

**Comment by courado** [comment]
Latest version on branch newtheme (to be merged with develop) has angular version 4.1.3, try it again with this and remember to `rm -rf node_modules` for a fresh install

**Comment by mhabsaoui** [comment]
Ok.

On click of "get started here" ==> it's just the OMTD web app front based on Angular (Enabling Layer maybe...). still no BO plugged, right ?

![image](https://user-images.githubusercontent.com/18755135/29712728-91447f1a-899b-11e7-9bef-c7af761e0e74.png)
