### ISSUE TITLE
[install] unmet peer dependency and error installing node-sass

### ISSUE THREAD

**Issue by jibe-b** [openminted/omtd-platform#4]
I am not an expert in nodejs and unsure where to go from here to install the package.

In branch newtheme (as it is the most advanced and suggested in #3 ), running 

`npm install`

I get 

>UNMET PEER DEPENDENCY file-loader@*

>UNMET PEER DEPENDENCY node-sass@*

and finally

>npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN bootstrap-loader@2.2.0 requires a peer of extract-text-webpack-plugin@>=2.1.0 but none was installed.
npm WARN url-loader@0.5.9 requires a peer of file-loader@* but none was installed.
npm WARN openminted-platform@1.0.0 No repository field.
npm ERR! Linux 4.4.0-98-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.

**Comment by jibe-b** [comment]
Full stdout:

>
>openminted-platform@1.0.0 /home/u/factory/omtd-platform
├─┬ @angular/common@4.4.6 
│ └── tslib@1.8.0 
├── @angular/compiler@4.4.6 
├─┬ @angular/compiler-cli@4.4.6 
│ ├─┬ @angular/tsc-wrapped@4.4.6 
│ │ └─┬ tsickle@0.21.6 
│ │   └── minimist@1.2.0 
│ └── minimist@1.2.0 
├── @angular/core@4.4.6 
├── @angular/forms@4.4.6 
├── @angular/http@4.4.6 
├── @angular/platform-browser@4.4.6 
├── @angular/platform-browser-dynamic@4.4.6 
├── @angular/router@4.4.6 
├── @angular/upgrade@4.4.6 
├─┬ @ngtools/webpack@1.8.0 
│ ├─┬ chalk@2.2.2 
│ │ ├── ansi-styles@3.2.0 
│ │ └─┬ supports-color@4.5.0 
│ │   └── has-flag@2.0.0 
│ ├── loader-utils@1.1.0 
│ ├─┬ magic-string@0.22.4 
│ │ └── vlq@0.2.3 
│ └── tree-kill@1.2.0 
├─┬ awesome-typescript-loader@3.3.0
│ └── loader-utils@1.1.0 
├─┬ bootstrap-loader@2.2.0
│ ├─┬ exports-loader@0.6.4
│ │ └── loader-utils@1.1.0 
│ └── loader-utils@1.1.0 
├─┬ css-loader@0.28.7
│ ├─┬ icss-utils@2.1.0
│ │ └─┬ postcss@6.0.14
│ │   ├─┬ chalk@2.3.0
│ │   │ └── ansi-styles@3.2.0 
│ │   ├── source-map@0.6.1 
│ │   └─┬ supports-color@4.5.0 
│ │     └── has-flag@2.0.0 
│ ├── loader-utils@1.1.0 
│ ├─┬ postcss-modules-extract-imports@1.1.0
│ │ └─┬ postcss@6.0.14
│ │   ├─┬ chalk@2.3.0
│ │   │ └── ansi-styles@3.2.0 
│ │   ├── source-map@0.6.1 
│ │   └─┬ supports-color@4.5.0 
│ │     └── has-flag@2.0.0 
│ ├─┬ postcss-modules-local-by-default@1.2.0
│ │ └─┬ postcss@6.0.14
│ │   ├─┬ chalk@2.3.0
│ │   │ └── ansi-styles@3.2.0 
│ │   ├── source-map@0.6.1 
│ │   └─┬ supports-color@4.5.0 
│ │     └── has-flag@2.0.0 
│ ├─┬ postcss-modules-scope@1.1.0
│ │ └─┬ postcss@6.0.14
│ │   ├─┬ chalk@2.3.0
│ │   │ └── ansi-styles@3.2.0 
│ │   ├── source-map@0.6.1 
│ │   └─┬ supports-color@4.5.0 
│ │     └── has-flag@2.0.0 
│ └─┬ postcss-modules-values@1.3.0
│   └─┬ postcss@6.0.14
│     ├─┬ chalk@2.3.0
│     │ └── ansi-styles@3.2.0 
│     ├── source-map@0.6.1 
│     └─┬ supports-color@4.5.0 
│       └── has-flag@2.0.0 
├── UNMET PEER DEPENDENCY extract-text-webpack-plugin@>=2.1.0
├── UNMET PEER DEPENDENCY file-loader@*
├─┬ html-webpack-plugin@2.30.1 
│ ├─┬ html-minifier@3.5.6 
│ │ ├─┬ camel-case@3.0.0 
│ │ │ ├─┬ no-case@2.3.2 
│ │ │ │ └── lower-case@1.1.4 
│ │ │ └── upper-case@1.1.3 
│ │ ├── clean-css@4.1.9 
│ │ ├── he@1.1.1 
│ │ ├─┬ ncname@1.0.0 
│ │ │ └── xml-char-classes@1.0.0 
│ │ ├── param-case@2.1.1 
│ │ └── relateurl@0.2.7 
│ ├─┬ pretty-error@2.1.1 
│ │ ├─┬ renderkid@2.0.1 
│ │ │ ├─┬ css-select@1.2.0 
│ │ │ │ ├── boolbase@1.0.0 
│ │ │ │ ├── css-what@2.1.0 
│ │ │ │ ├─┬ domutils@1.5.1 
│ │ │ │ │ └─┬ dom-serializer@0.1.0 
│ │ │ │ │   ├── domelementtype@1.1.3 
│ │ │ │ │   └── entities@1.1.1 
│ │ │ │ └── nth-check@1.0.1 
│ │ │ ├─┬ dom-converter@0.1.4 
│ │ │ │ └── utila@0.3.3 
│ │ │ ├─┬ htmlparser2@3.3.0 
│ │ │ │ ├── domelementtype@1.3.0 
│ │ │ │ ├── domhandler@2.1.0 
│ │ │ │ ├── domutils@1.1.6 
│ │ │ │ └─┬ readable-stream@1.0.34 
│ │ │ │   ├── isarray@0.0.1 
│ │ │ │   └── string_decoder@0.10.31 
│ │ │ └── utila@0.3.3 
│ │ └── utila@0.4.0 
│ └── toposort@1.0.6 
├─┬ lite-server@2.3.0
│ ├─┬ browser-sync@2.18.13
│ │ └─┬ socket.io@1.6.0
│ │   ├─┬ engine.io@1.8.0
│ │   │ └─┬ engine.io-parser@1.3.1
│ │   │   └─┬ has-binary@0.1.6
│ │   │     └── isarray@0.0.1 
│ │   ├─┬ has-binary@0.1.7
│ │   │ └── isarray@0.0.1 
│ │   └─┬ socket.io-parser@2.3.1
│ │     └── isarray@0.0.1 
│ └── minimist@1.2.0 
├─┬ ng2-ace-editor@0.2.5 
│ ├── ace-builds@1.2.9 
│ └─┬ brace@0.9.1 
│   └── w3c-blob@0.0.1 
├── UNMET PEER DEPENDENCY node-sass@*
├─┬ resolve-url-loader@2.2.0
│ ├─┬ adjust-sourcemap-loader@1.1.0
│ │ └── loader-utils@1.1.0 
│ └── loader-utils@1.1.0 
├─┬ sass-loader@6.0.6
│ └── loader-utils@1.1.0 
├─┬ style-loader@0.18.2
│ └── loader-utils@1.1.0 
├─┬ typings@2.1.1
│ ├── minimist@1.2.0 
│ ├─┬ typings-core@2.3.3
│ │ └─┬ rc@1.2.2
│ │   └── minimist@1.2.0 
│ └─┬ update-notifier@2.3.0
│   ├─┬ boxen@1.2.2
│   │ └─┬ chalk@2.3.0
│   │   ├── ansi-styles@3.2.0 
│   │   └─┬ supports-color@4.5.0 
│   │     └── has-flag@2.0.0 
│   └─┬ chalk@2.3.0
│     ├── ansi-styles@3.2.0 
│     └─┬ supports-color@4.5.0 
│       └── has-flag@2.0.0 
├─┬ uglify-es@3.1.6 
│ └── source-map@0.6.1 
├─┬ uglify-js@3.1.6
│ └── source-map@0.6.1 
├─┬ uglifyjs-webpack-plugin@0.4.6 
│ ├─┬ uglify-js@2.8.29 
│ │ └─┬ yargs@3.10.0 
│ │   ├─┬ cliui@2.1.0 
│ │   │ └── wordwrap@0.0.2 
│ │   └── window-size@0.1.0 
│ └── webpack-sources@1.0.1 
├─┬ url-loader@0.5.9
│ └── loader-utils@1.1.0 
└─┬ webpack@2.5.1
  ├─┬ node-libs-browser@2.0.0
  │ └── string_decoder@0.10.31 
  └─┬ uglify-js@2.8.29 
    └─┬ yargs@3.10.0 
      ├─┬ cliui@2.1.0 
      │ └── wordwrap@0.0.2 
      └── window-size@0.1.0 
>npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN bootstrap-loader@2.2.0 requires a peer of extract-text-webpack-plugin@>=2.1.0 but none was installed.
npm WARN url-loader@0.5.9 requires a peer of file-loader@* but none was installed.
npm WARN openminted-platform@1.0.0 No repository field.
npm ERR! Linux 4.4.0-98-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:

**Comment by courado** [comment]
```
npm ERR! node v4.2.6
npm ERR! npm v3.5.2
```
Your node installation is really old, try upgrading.
For reference, I'm using
```
node v7.2.0
npm  v3.10.9
```

**Comment by jibe-b** [comment]
Ok, updated to node 7.10.1 and it works fine. Thanks @courado.

There only are a few warnings about angularjs.

**Comment by jibe-b** [comment]
https://github.com/openminted/omtd-platform/pull/5 is a small suggestion.
